
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OAFComplex.Models.Shared
{
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using OAFComplex.Utils;
    using System.Numerics;
    using System;
    

    public class BodyScalarType
    {
        private BodyScalarType(string value) { Value = value; }

        public string Value { get; private set; }
        public static BodyScalarType Int32 { get { return new BodyScalarType("int32"); } }
        
        public static BodyScalarType Boolean { get { return new BodyScalarType("boolean"); } }
        
        public static BodyScalarType Str { get { return new BodyScalarType("str"); } }
        
        public static BodyScalarType Any { get { return new BodyScalarType("any"); } }
        
        public static BodyScalarType Null { get { return new BodyScalarType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(BodyScalarType v) { return v.Value; }
        public static BodyScalarType FromString(string v) {
            switch(v) {
                case "int32": return Int32;
                case "boolean": return Boolean;
                case "str": return Str;
                case "any": return Any;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for BodyScalarType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((BodyScalarType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }
    

    [JsonConverter(typeof(BodyScalar.BodyScalarConverter))]
    public class BodyScalar {
        public BodyScalar(BodyScalarType type) {
            Type = type;
        }
        public int? Int32 { get; set; } 
        public bool? Boolean { get; set; } 
        public string? Str { get; set; } 
        public object? Any { get; set; } 

        public BodyScalarType Type { get; set; }


        public static BodyScalar CreateInt32(int int32) {
            BodyScalarType typ = BodyScalarType.Int32;

            BodyScalar res = new BodyScalar(typ);
            res.Int32 = int32;
            return res;
        }

        public static BodyScalar CreateBoolean(bool boolean) {
            BodyScalarType typ = BodyScalarType.Boolean;

            BodyScalar res = new BodyScalar(typ);
            res.Boolean = boolean;
            return res;
        }

        public static BodyScalar CreateStr(string str) {
            BodyScalarType typ = BodyScalarType.Str;

            BodyScalar res = new BodyScalar(typ);
            res.Str = str;
            return res;
        }

        public static BodyScalar CreateAny(object any) {
            BodyScalarType typ = BodyScalarType.Any;

            BodyScalar res = new BodyScalar(typ);
            res.Any = any;
            return res;
        }

        public static BodyScalar CreateNull() {
            BodyScalarType typ = BodyScalarType.Null;
            return new BodyScalar(typ);
        }

        public class BodyScalarConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(BodyScalar);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            { 
                var json = JRaw.Create(reader).ToString();

                if (json == "null") {
                    return null;
                } 
                try {
                    var converted = Convert.ToInt32(json);
                    return new BodyScalar(BodyScalarType.Int32) {
                        Int32 = converted
                    };
                } catch (System.FormatException) {
                    // try next option
                } 
                try {
                    var converted = Convert.ToBoolean(json);
                    return new BodyScalar(BodyScalarType.Boolean) {
                        Boolean = converted
                    };
                } catch (System.FormatException) {
                    // try next option
                }
                if (json[0] == '"' && json[^1] == '"'){
                    return new BodyScalar(BodyScalarType.Str) {
                        Str = json[1..^1]
                    };
                }
                try
                {
                    object? any = JsonConvert.DeserializeObject<object>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(object))});
                    return new BodyScalar(BodyScalarType.Any) {
                        Any = any
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                BodyScalar res = (BodyScalar)value;
                if (BodyScalarType.FromString(res.Type).Equals(BodyScalarType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Int32 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Int32));
                    return;
                }
                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
                if (res.Any != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Any));
                    return;
                }

            }
        }

    }

}