
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OAFComplex.Models.Shared
{
    using Newtonsoft.Json;
    
    public class Car
    {

        [JsonProperty("HaveTrunk")]
        public bool HaveTrunk { get; set; } = default!;

        [JsonProperty("NumberOfTyres")]
        public string NumberOfTyres { get; set; } = default!;
    }
}