
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OAFComplex.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// A string enum representing days of the week
    /// </summary>
    public enum Days
    {
        [JsonProperty("Sunday")]
        Sunday,
        [JsonProperty("Monday")]
        Monday,
        [JsonProperty("Tuesday")]
        Tuesday,
        [JsonProperty("Wednesday")]
        Wednesday,
        [JsonProperty("Thursday")]
        Thursday,
        [JsonProperty("Friday")]
        Friday,
        [JsonProperty("Saturday")]
        Saturday,
    }

    public static class DaysExtension
    {
        public static string Value(this Days value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static Days ToEnum(this string value)
        {
            foreach(var field in typeof(Days).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is Days)
                    {
                        return (Days)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum Days");
        }
    }

}