
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OAFComplex.Models.Shared
{
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using OAFComplex.Models.Shared;
    using OAFComplex.Utils;
    using System.Numerics;
    using System;
    

    public class MixedModel1Type
    {
        private MixedModel1Type(string value) { Value = value; }

        public string Value { get; private set; }
        public static MixedModel1Type Car { get { return new MixedModel1Type("Car"); } }
        
        public static MixedModel1Type Str { get { return new MixedModel1Type("str"); } }
        
        public static MixedModel1Type Null { get { return new MixedModel1Type("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(MixedModel1Type v) { return v.Value; }
        public static MixedModel1Type FromString(string v) {
            switch(v) {
                case "Car": return Car;
                case "str": return Str;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for MixedModel1Type");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((MixedModel1Type)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }
    

    [JsonConverter(typeof(MixedModel1.MixedModel1Converter))]
    public class MixedModel1 {
        public MixedModel1(MixedModel1Type type) {
            Type = type;
        }
        public Car? Car { get; set; } 
        public string? Str { get; set; } 

        public MixedModel1Type Type { get; set; }


        public static MixedModel1 CreateCar(Car car) {
            MixedModel1Type typ = MixedModel1Type.Car;

            MixedModel1 res = new MixedModel1(typ);
            res.Car = car;
            return res;
        }

        public static MixedModel1 CreateStr(string str) {
            MixedModel1Type typ = MixedModel1Type.Str;

            MixedModel1 res = new MixedModel1(typ);
            res.Str = str;
            return res;
        }

        public static MixedModel1 CreateNull() {
            MixedModel1Type typ = MixedModel1Type.Null;
            return new MixedModel1(typ);
        }

        public class MixedModel1Converter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(MixedModel1);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            { 
                var json = JRaw.Create(reader).ToString();

                if (json == "null") {
                    return null;
                }
                try
                {
                    Car? car = JsonConvert.DeserializeObject<Car>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(Car))});
                    return new MixedModel1(MixedModel1Type.Car) {
                        Car = car
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                if (json[0] == '"' && json[^1] == '"'){
                    return new MixedModel1(MixedModel1Type.Str) {
                        Str = json[1..^1]
                    };
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                MixedModel1 res = (MixedModel1)value;
                if (MixedModel1Type.FromString(res.Type).Equals(MixedModel1Type.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Car != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Car));
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

            }
        }

    }

}