
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OAFComplex.Models.Shared
{
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using OAFComplex.Models.Shared;
    using OAFComplex.Utils;
    using System.Numerics;
    using System;
    

    public class MultiOneOfAnyOfType
    {
        private MultiOneOfAnyOfType(string value) { Value = value; }

        public string Value { get; private set; }
        public static MultiOneOfAnyOfType MixedModel1 { get { return new MultiOneOfAnyOfType("MixedModel_1"); } }
        
        public static MultiOneOfAnyOfType Morning { get { return new MultiOneOfAnyOfType("Morning"); } }
        
        public static MultiOneOfAnyOfType Null { get { return new MultiOneOfAnyOfType("null"); } } 

        public override string ToString() { return Value; }
        public static implicit operator String(MultiOneOfAnyOfType v) { return v.Value; }
        public static MultiOneOfAnyOfType FromString(string v) {
            switch(v) {
                case "MixedModel_1": return MixedModel1;
                case "Morning": return Morning;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for MultiOneOfAnyOfType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((MultiOneOfAnyOfType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }
    

    [JsonConverter(typeof(MultiOneOfAnyOf.MultiOneOfAnyOfConverter))]
    public class MultiOneOfAnyOf {
        public MultiOneOfAnyOf(MultiOneOfAnyOfType type) {
            Type = type;
        }
        public MixedModel1? MixedModel1 { get; set; } 
        public Morning? Morning { get; set; } 

        public MultiOneOfAnyOfType Type {get; set; }


        public static MultiOneOfAnyOf CreateMixedModel1(MixedModel1 mixedModel1) {
            MultiOneOfAnyOfType typ = MultiOneOfAnyOfType.MixedModel1;

            MultiOneOfAnyOf res = new MultiOneOfAnyOf(typ);
            res.MixedModel1 = mixedModel1;
            return res;
        }

        public static MultiOneOfAnyOf CreateMorning(Morning morning) {
            MultiOneOfAnyOfType typ = MultiOneOfAnyOfType.Morning;

            MultiOneOfAnyOf res = new MultiOneOfAnyOf(typ);
            res.Morning = morning;
            return res;
        }

        public static MultiOneOfAnyOf CreateNull() {
            MultiOneOfAnyOfType typ = MultiOneOfAnyOfType.Null;
            return new MultiOneOfAnyOf(typ);
        }

        public class MultiOneOfAnyOfConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(MultiOneOfAnyOf);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            { 
                var json = JRaw.Create(reader).ToString();

                if (json == "null") {
                    return null;
                }
                try
                {
                    Morning? morning = JsonConvert.DeserializeObject<Morning>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(Morning), "string")});
                    return new MultiOneOfAnyOf(MultiOneOfAnyOfType.Morning) {
                        Morning = morning
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    MixedModel1? mixedModel1 = JsonConvert.DeserializeObject<MixedModel1>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(MixedModel1), "string")});
                    return new MultiOneOfAnyOf(MultiOneOfAnyOfType.MixedModel1) {
                        MixedModel1 = mixedModel1
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                MultiOneOfAnyOf res = (MultiOneOfAnyOf)value;
                if (MultiOneOfAnyOfType.FromString(res.Type).Equals(MultiOneOfAnyOfType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.MixedModel1 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.MixedModel1));
                    return;
                }
                if (res.Morning != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Morning));
                    return;
                }

            }
        }

    }


}