
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OAFComplex.Models.Shared
{
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using OAFComplex.Models.Shared;
    using OAFComplex.Utils;
    using System.Numerics;
    using System;
    

    public class NonScalarModelSchemas1Type
    {
        private NonScalarModelSchemas1Type(string value) { Value = value; }

        public string Value { get; private set; }
        public static NonScalarModelSchemas1Type Car { get { return new NonScalarModelSchemas1Type("Car"); } }
        
        public static NonScalarModelSchemas1Type Atom { get { return new NonScalarModelSchemas1Type("Atom"); } }
        
        public static NonScalarModelSchemas1Type Null { get { return new NonScalarModelSchemas1Type("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(NonScalarModelSchemas1Type v) { return v.Value; }
        public static NonScalarModelSchemas1Type FromString(string v) {
            switch(v) {
                case "Car": return Car;
                case "Atom": return Atom;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for NonScalarModelSchemas1Type");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((NonScalarModelSchemas1Type)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }
    

    [JsonConverter(typeof(NonScalarModelSchemas1.NonScalarModelSchemas1Converter))]
    public class NonScalarModelSchemas1 {
        public NonScalarModelSchemas1(NonScalarModelSchemas1Type type) {
            Type = type;
        }
        public Car? Car { get; set; } 
        public Atom? Atom { get; set; } 

        public NonScalarModelSchemas1Type Type { get; set; }


        public static NonScalarModelSchemas1 CreateCar(Car car) {
            NonScalarModelSchemas1Type typ = NonScalarModelSchemas1Type.Car;

            NonScalarModelSchemas1 res = new NonScalarModelSchemas1(typ);
            res.Car = car;
            return res;
        }

        public static NonScalarModelSchemas1 CreateAtom(Atom atom) {
            NonScalarModelSchemas1Type typ = NonScalarModelSchemas1Type.Atom;

            NonScalarModelSchemas1 res = new NonScalarModelSchemas1(typ);
            res.Atom = atom;
            return res;
        }

        public static NonScalarModelSchemas1 CreateNull() {
            NonScalarModelSchemas1Type typ = NonScalarModelSchemas1Type.Null;
            return new NonScalarModelSchemas1(typ);
        }

        public class NonScalarModelSchemas1Converter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(NonScalarModelSchemas1);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            { 
                var json = JRaw.Create(reader).ToString();

                if (json == "null") {
                    return null;
                }
                try
                {
                    Car? car = JsonConvert.DeserializeObject<Car>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(Car))});
                    return new NonScalarModelSchemas1(NonScalarModelSchemas1Type.Car) {
                        Car = car
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    Atom? atom = JsonConvert.DeserializeObject<Atom>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(Atom))});
                    return new NonScalarModelSchemas1(NonScalarModelSchemas1Type.Atom) {
                        Atom = atom
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                NonScalarModelSchemas1 res = (NonScalarModelSchemas1)value;
                if (NonScalarModelSchemas1Type.FromString(res.Type).Equals(NonScalarModelSchemas1Type.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Car != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Car));
                    return;
                }
                if (res.Atom != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Atom));
                    return;
                }

            }
        }

    }

}