
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OAFComplex.Models.Shared
{
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using OAFComplex.Models.Shared;
    using OAFComplex.Utils;
    using System.Numerics;
    using System;
    

    public class NonScalarModel1Type
    {
        private NonScalarModel1Type(string value) { Value = value; }

        public string Value { get; private set; }
        public static NonScalarModel1Type Car { get { return new NonScalarModel1Type("Car"); } }
        
        public static NonScalarModel1Type Atom { get { return new NonScalarModel1Type("Atom"); } }
        
        public static NonScalarModel1Type Null { get { return new NonScalarModel1Type("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(NonScalarModel1Type v) { return v.Value; }
        public static NonScalarModel1Type FromString(string v) {
            switch(v) {
                case "Car": return Car;
                case "Atom": return Atom;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for NonScalarModel1Type");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((NonScalarModel1Type)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }
    

    [JsonConverter(typeof(NonScalarModel1.NonScalarModel1Converter))]
    public class NonScalarModel1 {
        public NonScalarModel1(NonScalarModel1Type type) {
            Type = type;
        }
        public Car? Car { get; set; } 
        public Atom? Atom { get; set; } 

        public NonScalarModel1Type Type { get; set; }


        public static NonScalarModel1 CreateCar(Car car) {
            NonScalarModel1Type typ = NonScalarModel1Type.Car;

            NonScalarModel1 res = new NonScalarModel1(typ);
            res.Car = car;
            return res;
        }

        public static NonScalarModel1 CreateAtom(Atom atom) {
            NonScalarModel1Type typ = NonScalarModel1Type.Atom;

            NonScalarModel1 res = new NonScalarModel1(typ);
            res.Atom = atom;
            return res;
        }

        public static NonScalarModel1 CreateNull() {
            NonScalarModel1Type typ = NonScalarModel1Type.Null;
            return new NonScalarModel1(typ);
        }

        public class NonScalarModel1Converter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(NonScalarModel1);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            { 
                var json = JRaw.Create(reader).ToString();

                if (json == "null") {
                    return null;
                }
                try
                {
                    Car? car = ResponseBodyDeserializer.Deserialize<Car>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new NonScalarModel1(NonScalarModel1Type.Car) {
                        Car = car
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    Atom? atom = ResponseBodyDeserializer.Deserialize<Atom>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new NonScalarModel1(NonScalarModel1Type.Atom) {
                        Atom = atom
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                NonScalarModel1 res = (NonScalarModel1)value;
                if (NonScalarModel1Type.FromString(res.Type).Equals(NonScalarModel1Type.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Car != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Car));
                    return;
                }
                if (res.Atom != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Atom));
                    return;
                }

            }
        }

    }

}