
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OAFComplex.Models.Shared
{
    using Newtonsoft.Json;
    using OAFComplex.Models.Shared;
    using System.Collections.Generic;
    
    /// <summary>
    /// This class contains non scalar types in oneOf/anyOf cases.
    /// </summary>
    public class NonScalarModel
    {

        [JsonProperty("allInnerArrayOfMap", NullValueHandling = NullValueHandling.Include)]
        public NonScalarModelAllInnerArrayOfMap? AllInnerArrayOfMap { get; set; } = default!;

        [JsonProperty("allInnerArrayOfMap2", NullValueHandling = NullValueHandling.Include)]
        public Dictionary<string, NonScalarModelAllInnerArrayOfMap2>? AllInnerArrayOfMap2 { get; set; } = default!;

        [JsonProperty("multiAnyOf")]
        public NonScalarModelMultiAnyOf MultiAnyOf { get; set; } = default!;

        [JsonProperty("multiOneOfAnyOf")]
        public NonScalarModelMultiOneOfAnyOf MultiOneOfAnyOf { get; set; } = default!;

        [JsonProperty("outerArrayOfMap")]
        public List<Dictionary<string, NonScalarModelOuterArrayOfMap>>? OuterArrayOfMap { get; set; }

        [JsonProperty("outerArrayOfMap2")]
        public List<Dictionary<string, List<Car>>>? OuterArrayOfMap2 { get; set; }

        [JsonProperty("outerMapOfArray")]
        public Dictionary<string, List<NonScalarModelOuterMapOfArray>>? OuterMapOfArray { get; set; }

        [JsonProperty("outerMapOfArray2")]
        public Dictionary<string, List<NonScalarModelOuterMapOfArray2>>? OuterMapOfArray2 { get; set; }

        [JsonProperty("outerMapOfSingleInnerArray")]
        public Dictionary<string, NonScalarModelOuterMapOfSingleInnerArray> OuterMapOfSingleInnerArray { get; set; } = default!;

        [JsonProperty("singleInnerMapOfArray")]
        public NonScalarModelSingleInnerMapOfArray SingleInnerMapOfArray { get; set; } = default!;
    }
}