
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OAFComplex.Models.Shared
{
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using OAFComplex.Models.Shared;
    using OAFComplex.Utils;
    using System.Collections.Generic;
    using System.Numerics;
    using System;
    

    public class NonScalarModelAllInnerArrayOfMap2Type
    {
        private NonScalarModelAllInnerArrayOfMap2Type(string value) { Value = value; }

        public string Value { get; private set; }
        public static NonScalarModelAllInnerArrayOfMap2Type ArrayOfmapOfOrbit { get { return new NonScalarModelAllInnerArrayOfMap2Type("arrayOfmapOfOrbit"); } }
        
        public static NonScalarModelAllInnerArrayOfMap2Type ArrayOfmapOfVehicle { get { return new NonScalarModelAllInnerArrayOfMap2Type("arrayOfmapOfVehicle"); } }
        
        public static NonScalarModelAllInnerArrayOfMap2Type Any { get { return new NonScalarModelAllInnerArrayOfMap2Type("any"); } }
        
        public static NonScalarModelAllInnerArrayOfMap2Type Null { get { return new NonScalarModelAllInnerArrayOfMap2Type("null"); } } 

        public override string ToString() { return Value; }
        public static implicit operator String(NonScalarModelAllInnerArrayOfMap2Type v) { return v.Value; }
        public static NonScalarModelAllInnerArrayOfMap2Type FromString(string v) {
            switch(v) {
                case "arrayOfmapOfOrbit": return ArrayOfmapOfOrbit;
                case "arrayOfmapOfVehicle": return ArrayOfmapOfVehicle;
                case "any": return Any;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for NonScalarModelAllInnerArrayOfMap2Type");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((NonScalarModelAllInnerArrayOfMap2Type)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }
    

    [JsonConverter(typeof(NonScalarModelAllInnerArrayOfMap2.NonScalarModelAllInnerArrayOfMap2Converter))]
    public class NonScalarModelAllInnerArrayOfMap2 {
        public NonScalarModelAllInnerArrayOfMap2(NonScalarModelAllInnerArrayOfMap2Type type) {
            Type = type;
        }
        public List<Dictionary<string, Orbit>>? ArrayOfmapOfOrbit { get; set; } 
        public List<Dictionary<string, Vehicle>>? ArrayOfmapOfVehicle { get; set; } 
        public object? Any { get; set; } 

        public NonScalarModelAllInnerArrayOfMap2Type Type {get; set; }


        public static NonScalarModelAllInnerArrayOfMap2 CreateArrayOfmapOfOrbit(List<Dictionary<string, Orbit>> arrayOfmapOfOrbit) {
            NonScalarModelAllInnerArrayOfMap2Type typ = NonScalarModelAllInnerArrayOfMap2Type.ArrayOfmapOfOrbit;

            NonScalarModelAllInnerArrayOfMap2 res = new NonScalarModelAllInnerArrayOfMap2(typ);
            res.ArrayOfmapOfOrbit = arrayOfmapOfOrbit;
            return res;
        }

        public static NonScalarModelAllInnerArrayOfMap2 CreateArrayOfmapOfVehicle(List<Dictionary<string, Vehicle>> arrayOfmapOfVehicle) {
            NonScalarModelAllInnerArrayOfMap2Type typ = NonScalarModelAllInnerArrayOfMap2Type.ArrayOfmapOfVehicle;

            NonScalarModelAllInnerArrayOfMap2 res = new NonScalarModelAllInnerArrayOfMap2(typ);
            res.ArrayOfmapOfVehicle = arrayOfmapOfVehicle;
            return res;
        }

        public static NonScalarModelAllInnerArrayOfMap2 CreateAny(object any) {
            NonScalarModelAllInnerArrayOfMap2Type typ = NonScalarModelAllInnerArrayOfMap2Type.Any;

            NonScalarModelAllInnerArrayOfMap2 res = new NonScalarModelAllInnerArrayOfMap2(typ);
            res.Any = any;
            return res;
        }

        public static NonScalarModelAllInnerArrayOfMap2 CreateNull() {
            NonScalarModelAllInnerArrayOfMap2Type typ = NonScalarModelAllInnerArrayOfMap2Type.Null;
            return new NonScalarModelAllInnerArrayOfMap2(typ);
        }

        public class NonScalarModelAllInnerArrayOfMap2Converter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(NonScalarModelAllInnerArrayOfMap2);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            { 
                var json = JRaw.Create(reader).ToString();

                if (json == "null") {
                    return null;
                }
                try
                {
                    List<Dictionary<string, Orbit>>? arrayOfmapOfOrbit = JsonConvert.DeserializeObject<List<Dictionary<string, Orbit>>>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(List<Dictionary<string, Orbit>>), "string")});
                    return new NonScalarModelAllInnerArrayOfMap2(NonScalarModelAllInnerArrayOfMap2Type.ArrayOfmapOfOrbit) {
                        ArrayOfmapOfOrbit = arrayOfmapOfOrbit
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    List<Dictionary<string, Vehicle>>? arrayOfmapOfVehicle = JsonConvert.DeserializeObject<List<Dictionary<string, Vehicle>>>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(List<Dictionary<string, Vehicle>>), "string")});
                    return new NonScalarModelAllInnerArrayOfMap2(NonScalarModelAllInnerArrayOfMap2Type.ArrayOfmapOfVehicle) {
                        ArrayOfmapOfVehicle = arrayOfmapOfVehicle
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    object? any = JsonConvert.DeserializeObject<object>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(object), "string")});
                    return new NonScalarModelAllInnerArrayOfMap2(NonScalarModelAllInnerArrayOfMap2Type.Any) {
                        Any = any
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                NonScalarModelAllInnerArrayOfMap2 res = (NonScalarModelAllInnerArrayOfMap2)value;
                if (NonScalarModelAllInnerArrayOfMap2Type.FromString(res.Type).Equals(NonScalarModelAllInnerArrayOfMap2Type.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.ArrayOfmapOfOrbit != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfmapOfOrbit));
                    return;
                }
                if (res.ArrayOfmapOfVehicle != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfmapOfVehicle));
                    return;
                }
                if (res.Any != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Any));
                    return;
                }

            }
        }

    }


}