
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OAFComplex.Models.Shared
{
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using OAFComplex.Models.Shared;
    using OAFComplex.Utils;
    using System.Numerics;
    using System;
    

    public class NonScalarModelMultiAnyOfType
    {
        private NonScalarModelMultiAnyOfType(string value) { Value = value; }

        public string Value { get; private set; }
        public static NonScalarModelMultiAnyOfType NonScalarModel1 { get { return new NonScalarModelMultiAnyOfType("NonScalarModel_1"); } }
        
        public static NonScalarModelMultiAnyOfType Morning { get { return new NonScalarModelMultiAnyOfType("Morning"); } }
        
        public static NonScalarModelMultiAnyOfType Null { get { return new NonScalarModelMultiAnyOfType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(NonScalarModelMultiAnyOfType v) { return v.Value; }
        public static NonScalarModelMultiAnyOfType FromString(string v) {
            switch(v) {
                case "NonScalarModel_1": return NonScalarModel1;
                case "Morning": return Morning;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for NonScalarModelMultiAnyOfType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((NonScalarModelMultiAnyOfType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }
    

    [JsonConverter(typeof(NonScalarModelMultiAnyOf.NonScalarModelMultiAnyOfConverter))]
    public class NonScalarModelMultiAnyOf {
        public NonScalarModelMultiAnyOf(NonScalarModelMultiAnyOfType type) {
            Type = type;
        }
        public NonScalarModel1? NonScalarModel1 { get; set; } 
        public Morning? Morning { get; set; } 

        public NonScalarModelMultiAnyOfType Type { get; set; }


        public static NonScalarModelMultiAnyOf CreateNonScalarModel1(NonScalarModel1 nonScalarModel1) {
            NonScalarModelMultiAnyOfType typ = NonScalarModelMultiAnyOfType.NonScalarModel1;

            NonScalarModelMultiAnyOf res = new NonScalarModelMultiAnyOf(typ);
            res.NonScalarModel1 = nonScalarModel1;
            return res;
        }

        public static NonScalarModelMultiAnyOf CreateMorning(Morning morning) {
            NonScalarModelMultiAnyOfType typ = NonScalarModelMultiAnyOfType.Morning;

            NonScalarModelMultiAnyOf res = new NonScalarModelMultiAnyOf(typ);
            res.Morning = morning;
            return res;
        }

        public static NonScalarModelMultiAnyOf CreateNull() {
            NonScalarModelMultiAnyOfType typ = NonScalarModelMultiAnyOfType.Null;
            return new NonScalarModelMultiAnyOf(typ);
        }

        public class NonScalarModelMultiAnyOfConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(NonScalarModelMultiAnyOf);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            { 
                var json = JRaw.Create(reader).ToString();

                if (json == "null") {
                    return null;
                }
                try
                {
                    Morning? morning = JsonConvert.DeserializeObject<Morning>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(Morning))});
                    return new NonScalarModelMultiAnyOf(NonScalarModelMultiAnyOfType.Morning) {
                        Morning = morning
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    NonScalarModel1? nonScalarModel1 = JsonConvert.DeserializeObject<NonScalarModel1>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(NonScalarModel1))});
                    return new NonScalarModelMultiAnyOf(NonScalarModelMultiAnyOfType.NonScalarModel1) {
                        NonScalarModel1 = nonScalarModel1
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                NonScalarModelMultiAnyOf res = (NonScalarModelMultiAnyOf)value;
                if (NonScalarModelMultiAnyOfType.FromString(res.Type).Equals(NonScalarModelMultiAnyOfType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.NonScalarModel1 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.NonScalarModel1));
                    return;
                }
                if (res.Morning != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Morning));
                    return;
                }

            }
        }

    }

}