
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OAFComplex.Models.Shared
{
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using OAFComplex.Models.Shared;
    using OAFComplex.Utils;
    using System.Numerics;
    using System;
    

    public class NonScalarModelOuterArrayOfMapType
    {
        private NonScalarModelOuterArrayOfMapType(string value) { Value = value; }

        public string Value { get; private set; }
        public static NonScalarModelOuterArrayOfMapType Car { get { return new NonScalarModelOuterArrayOfMapType("Car"); } }
        
        public static NonScalarModelOuterArrayOfMapType Morning { get { return new NonScalarModelOuterArrayOfMapType("Morning"); } }
        
        public static NonScalarModelOuterArrayOfMapType Atom { get { return new NonScalarModelOuterArrayOfMapType("Atom"); } }
        
        public static NonScalarModelOuterArrayOfMapType Null { get { return new NonScalarModelOuterArrayOfMapType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(NonScalarModelOuterArrayOfMapType v) { return v.Value; }
        public static NonScalarModelOuterArrayOfMapType FromString(string v) {
            switch(v) {
                case "Car": return Car;
                case "Morning": return Morning;
                case "Atom": return Atom;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for NonScalarModelOuterArrayOfMapType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((NonScalarModelOuterArrayOfMapType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }
    

    [JsonConverter(typeof(NonScalarModelOuterArrayOfMap.NonScalarModelOuterArrayOfMapConverter))]
    public class NonScalarModelOuterArrayOfMap {
        public NonScalarModelOuterArrayOfMap(NonScalarModelOuterArrayOfMapType type) {
            Type = type;
        }
        public Car? Car { get; set; } 
        public Morning? Morning { get; set; } 
        public Atom? Atom { get; set; } 

        public NonScalarModelOuterArrayOfMapType Type { get; set; }


        public static NonScalarModelOuterArrayOfMap CreateCar(Car car) {
            NonScalarModelOuterArrayOfMapType typ = NonScalarModelOuterArrayOfMapType.Car;

            NonScalarModelOuterArrayOfMap res = new NonScalarModelOuterArrayOfMap(typ);
            res.Car = car;
            return res;
        }

        public static NonScalarModelOuterArrayOfMap CreateMorning(Morning morning) {
            NonScalarModelOuterArrayOfMapType typ = NonScalarModelOuterArrayOfMapType.Morning;

            NonScalarModelOuterArrayOfMap res = new NonScalarModelOuterArrayOfMap(typ);
            res.Morning = morning;
            return res;
        }

        public static NonScalarModelOuterArrayOfMap CreateAtom(Atom atom) {
            NonScalarModelOuterArrayOfMapType typ = NonScalarModelOuterArrayOfMapType.Atom;

            NonScalarModelOuterArrayOfMap res = new NonScalarModelOuterArrayOfMap(typ);
            res.Atom = atom;
            return res;
        }

        public static NonScalarModelOuterArrayOfMap CreateNull() {
            NonScalarModelOuterArrayOfMapType typ = NonScalarModelOuterArrayOfMapType.Null;
            return new NonScalarModelOuterArrayOfMap(typ);
        }

        public class NonScalarModelOuterArrayOfMapConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(NonScalarModelOuterArrayOfMap);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            { 
                var json = JRaw.Create(reader).ToString();

                if (json == "null") {
                    return null;
                }
                try
                {
                    Car? car = JsonConvert.DeserializeObject<Car>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(Car))});
                    return new NonScalarModelOuterArrayOfMap(NonScalarModelOuterArrayOfMapType.Car) {
                        Car = car
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    Atom? atom = JsonConvert.DeserializeObject<Atom>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(Atom))});
                    return new NonScalarModelOuterArrayOfMap(NonScalarModelOuterArrayOfMapType.Atom) {
                        Atom = atom
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    Morning? morning = JsonConvert.DeserializeObject<Morning>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(Morning))});
                    return new NonScalarModelOuterArrayOfMap(NonScalarModelOuterArrayOfMapType.Morning) {
                        Morning = morning
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                NonScalarModelOuterArrayOfMap res = (NonScalarModelOuterArrayOfMap)value;
                if (NonScalarModelOuterArrayOfMapType.FromString(res.Type).Equals(NonScalarModelOuterArrayOfMapType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Car != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Car));
                    return;
                }
                if (res.Morning != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Morning));
                    return;
                }
                if (res.Atom != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Atom));
                    return;
                }

            }
        }

    }

}