
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OAFComplex.Models.Shared
{
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using OAFComplex.Models.Shared;
    using OAFComplex.Utils;
    using System.Numerics;
    using System;
    

    public class OneType
    {
        private OneType(string value) { Value = value; }

        public string Value { get; private set; }
        public static OneType Car { get { return new OneType("Car"); } }
        
        public static OneType Str { get { return new OneType("str"); } }
        
        public static OneType Null { get { return new OneType("null"); } } 

        public override string ToString() { return Value; }
        public static implicit operator String(OneType v) { return v.Value; }
        public static OneType FromString(string v) {
            switch(v) {
                case "Car": return Car;
                case "str": return Str;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for OneType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((OneType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }
    

    [JsonConverter(typeof(One.OneConverter))]
    public class One {
        public One(OneType type) {
            Type = type;
        }
        public Car? Car { get; set; } 
        public string? Str { get; set; } 

        public OneType Type {get; set; }


        public static One CreateCar(Car car) {
            OneType typ = OneType.Car;

            One res = new One(typ);
            res.Car = car;
            return res;
        }

        public static One CreateStr(string str) {
            OneType typ = OneType.Str;

            One res = new One(typ);
            res.Str = str;
            return res;
        }

        public static One CreateNull() {
            OneType typ = OneType.Null;
            return new One(typ);
        }

        public class OneConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(One);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            { 
                var json = JRaw.Create(reader).ToString();

                if (json == "null") {
                    return null;
                }
                try
                {
                    Car? car = JsonConvert.DeserializeObject<Car>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(Car), "string")});
                    return new One(OneType.Car) {
                        Car = car
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                if (json[0] == '"' && json[^1] == '"'){
                    return new One(OneType.Str) {
                        Str = json[1..^1]
                    };
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                One res = (One)value;
                if (OneType.FromString(res.Type).Equals(OneType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Car != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Car));
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

            }
        }

    }


}