
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OAFComplex.Models.Shared
{
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using OAFComplex.Models.Shared;
    using OAFComplex.Utils;
    using System.Numerics;
    using System;
    

    public class OuterArrayOfMapType
    {
        private OuterArrayOfMapType(string value) { Value = value; }

        public string Value { get; private set; }
        public static OuterArrayOfMapType Car { get { return new OuterArrayOfMapType("Car"); } }
        
        public static OuterArrayOfMapType Morning { get { return new OuterArrayOfMapType("Morning"); } }
        
        public static OuterArrayOfMapType Str { get { return new OuterArrayOfMapType("str"); } }
        
        public static OuterArrayOfMapType Null { get { return new OuterArrayOfMapType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(OuterArrayOfMapType v) { return v.Value; }
        public static OuterArrayOfMapType FromString(string v) {
            switch(v) {
                case "Car": return Car;
                case "Morning": return Morning;
                case "str": return Str;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for OuterArrayOfMapType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((OuterArrayOfMapType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }
    

    [JsonConverter(typeof(OuterArrayOfMap.OuterArrayOfMapConverter))]
    public class OuterArrayOfMap {
        public OuterArrayOfMap(OuterArrayOfMapType type) {
            Type = type;
        }
        public Car? Car { get; set; } 
        public Morning? Morning { get; set; } 
        public string? Str { get; set; } 

        public OuterArrayOfMapType Type { get; set; }


        public static OuterArrayOfMap CreateCar(Car car) {
            OuterArrayOfMapType typ = OuterArrayOfMapType.Car;

            OuterArrayOfMap res = new OuterArrayOfMap(typ);
            res.Car = car;
            return res;
        }

        public static OuterArrayOfMap CreateMorning(Morning morning) {
            OuterArrayOfMapType typ = OuterArrayOfMapType.Morning;

            OuterArrayOfMap res = new OuterArrayOfMap(typ);
            res.Morning = morning;
            return res;
        }

        public static OuterArrayOfMap CreateStr(string str) {
            OuterArrayOfMapType typ = OuterArrayOfMapType.Str;

            OuterArrayOfMap res = new OuterArrayOfMap(typ);
            res.Str = str;
            return res;
        }

        public static OuterArrayOfMap CreateNull() {
            OuterArrayOfMapType typ = OuterArrayOfMapType.Null;
            return new OuterArrayOfMap(typ);
        }

        public class OuterArrayOfMapConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(OuterArrayOfMap);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            { 
                var json = JRaw.Create(reader).ToString();

                if (json == "null") {
                    return null;
                }
                try
                {
                    Car? car = JsonConvert.DeserializeObject<Car>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(Car))});
                    return new OuterArrayOfMap(OuterArrayOfMapType.Car) {
                        Car = car
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    Morning? morning = JsonConvert.DeserializeObject<Morning>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(Morning))});
                    return new OuterArrayOfMap(OuterArrayOfMapType.Morning) {
                        Morning = morning
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                if (json[0] == '"' && json[^1] == '"'){
                    return new OuterArrayOfMap(OuterArrayOfMapType.Str) {
                        Str = json[1..^1]
                    };
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                OuterArrayOfMap res = (OuterArrayOfMap)value;
                if (OuterArrayOfMapType.FromString(res.Type).Equals(OuterArrayOfMapType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Car != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Car));
                    return;
                }
                if (res.Morning != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Morning));
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

            }
        }

    }

}