
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OAFComplex.Models.Shared
{
    using Newtonsoft.Json;
    using NodaTime;
    using System;
    
    public class Person
    {

        [JsonProperty("address")]
        public string Address { get; set; } = default!;

        [JsonProperty("age")]
        public long Age { get; set; } = default!;

        [JsonProperty("birthday")]
        public LocalDate Birthday { get; set; } = default!;

        [JsonProperty("birthtime")]
        public DateTime Birthtime { get; set; } = default!;

        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        [JsonProperty("personType")]
        public string PersonType { get; set; } = default!;

        [JsonProperty("uid")]
        public string Uid { get; set; } = default!;
    }
}