
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OAFComplex.Models.Shared
{
    using Newtonsoft.Json;
    using NodaTime;
    using OAFComplex.Models.Shared;
    using System.Collections.Generic;
    using System;
    
    public class Postman
    {

        [JsonProperty("address")]
        public string Address { get; set; } = default!;

        [JsonProperty("age")]
        public long Age { get; set; } = default!;

        [JsonProperty("birthday")]
        public LocalDate Birthday { get; set; } = default!;

        [JsonProperty("birthtime")]
        public DateTime Birthtime { get; set; } = default!;

        [JsonProperty("department")]
        public string Department { get; set; } = default!;

        [JsonProperty("dependents")]
        public List<Person> Dependents { get; set; } = default!;

        [JsonProperty("hiredAt")]
        public string HiredAt { get; set; } = default!;

        /// <summary>
        /// A string enum representing days of the week
        /// </summary>
        [JsonProperty("joiningDay")]
        public Days JoiningDay { get; set; } = default!;

        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        [JsonProperty("personType")]
        public string PersonType { get; set; } = default!;

        [JsonProperty("salary")]
        public int Salary { get; set; } = default!;

        [JsonProperty("uid")]
        public string Uid { get; set; } = default!;

        [JsonProperty("workingDays")]
        public List<Days> WorkingDays { get; set; } = default!;
    }
}