
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OAFComplex.Models.Shared
{
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using OAFComplex.Utils;
    using System.Numerics;
    using System;
    

    public class SendCombinedRequestBodyBodyScalarType
    {
        private SendCombinedRequestBodyBodyScalarType(string value) { Value = value; }

        public string Value { get; private set; }
        public static SendCombinedRequestBodyBodyScalarType Int32 { get { return new SendCombinedRequestBodyBodyScalarType("int32"); } }
        
        public static SendCombinedRequestBodyBodyScalarType Boolean { get { return new SendCombinedRequestBodyBodyScalarType("boolean"); } }
        
        public static SendCombinedRequestBodyBodyScalarType Str { get { return new SendCombinedRequestBodyBodyScalarType("str"); } }
        
        public static SendCombinedRequestBodyBodyScalarType Any { get { return new SendCombinedRequestBodyBodyScalarType("any"); } }
        
        public static SendCombinedRequestBodyBodyScalarType Null { get { return new SendCombinedRequestBodyBodyScalarType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(SendCombinedRequestBodyBodyScalarType v) { return v.Value; }
        public static SendCombinedRequestBodyBodyScalarType FromString(string v) {
            switch(v) {
                case "int32": return Int32;
                case "boolean": return Boolean;
                case "str": return Str;
                case "any": return Any;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for SendCombinedRequestBodyBodyScalarType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((SendCombinedRequestBodyBodyScalarType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }
    

    [JsonConverter(typeof(SendCombinedRequestBodyBodyScalar.SendCombinedRequestBodyBodyScalarConverter))]
    public class SendCombinedRequestBodyBodyScalar {
        public SendCombinedRequestBodyBodyScalar(SendCombinedRequestBodyBodyScalarType type) {
            Type = type;
        }
        public int? Int32 { get; set; } 
        public bool? Boolean { get; set; } 
        public string? Str { get; set; } 
        public object? Any { get; set; } 

        public SendCombinedRequestBodyBodyScalarType Type { get; set; }


        public static SendCombinedRequestBodyBodyScalar CreateInt32(int int32) {
            SendCombinedRequestBodyBodyScalarType typ = SendCombinedRequestBodyBodyScalarType.Int32;

            SendCombinedRequestBodyBodyScalar res = new SendCombinedRequestBodyBodyScalar(typ);
            res.Int32 = int32;
            return res;
        }

        public static SendCombinedRequestBodyBodyScalar CreateBoolean(bool boolean) {
            SendCombinedRequestBodyBodyScalarType typ = SendCombinedRequestBodyBodyScalarType.Boolean;

            SendCombinedRequestBodyBodyScalar res = new SendCombinedRequestBodyBodyScalar(typ);
            res.Boolean = boolean;
            return res;
        }

        public static SendCombinedRequestBodyBodyScalar CreateStr(string str) {
            SendCombinedRequestBodyBodyScalarType typ = SendCombinedRequestBodyBodyScalarType.Str;

            SendCombinedRequestBodyBodyScalar res = new SendCombinedRequestBodyBodyScalar(typ);
            res.Str = str;
            return res;
        }

        public static SendCombinedRequestBodyBodyScalar CreateAny(object any) {
            SendCombinedRequestBodyBodyScalarType typ = SendCombinedRequestBodyBodyScalarType.Any;

            SendCombinedRequestBodyBodyScalar res = new SendCombinedRequestBodyBodyScalar(typ);
            res.Any = any;
            return res;
        }

        public static SendCombinedRequestBodyBodyScalar CreateNull() {
            SendCombinedRequestBodyBodyScalarType typ = SendCombinedRequestBodyBodyScalarType.Null;
            return new SendCombinedRequestBodyBodyScalar(typ);
        }

        public class SendCombinedRequestBodyBodyScalarConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(SendCombinedRequestBodyBodyScalar);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            { 
                var json = JRaw.Create(reader).ToString();

                if (json == "null") {
                    return null;
                } 
                try {
                    var converted = Convert.ToInt32(json);
                    return new SendCombinedRequestBodyBodyScalar(SendCombinedRequestBodyBodyScalarType.Int32) {
                        Int32 = converted
                    };
                } catch (System.FormatException) {
                    // try next option
                } 
                try {
                    var converted = Convert.ToBoolean(json);
                    return new SendCombinedRequestBodyBodyScalar(SendCombinedRequestBodyBodyScalarType.Boolean) {
                        Boolean = converted
                    };
                } catch (System.FormatException) {
                    // try next option
                }
                if (json[0] == '"' && json[^1] == '"'){
                    return new SendCombinedRequestBodyBodyScalar(SendCombinedRequestBodyBodyScalarType.Str) {
                        Str = json[1..^1]
                    };
                }
                try
                {
                    object? any = JsonConvert.DeserializeObject<object>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(object))});
                    return new SendCombinedRequestBodyBodyScalar(SendCombinedRequestBodyBodyScalarType.Any) {
                        Any = any
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                SendCombinedRequestBodyBodyScalar res = (SendCombinedRequestBodyBodyScalar)value;
                if (SendCombinedRequestBodyBodyScalarType.FromString(res.Type).Equals(SendCombinedRequestBodyBodyScalarType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Int32 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Int32));
                    return;
                }
                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
                if (res.Any != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Any));
                    return;
                }

            }
        }

    }

}