
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OAFComplex.Models.Shared
{
    using Newtonsoft.Json;
    
    public class SendinModelRequestBody
    {

        /// <summary>
        /// This class contains mix of scalar and non scalar types in oneOf/anyOf cases.
        /// </summary>
        [JsonProperty("mixedModel")]
        public MixedModel MixedModel { get; set; } = default!;

        /// <summary>
        /// This class contains non scalar types in oneOf/anyOf cases.
        /// </summary>
        [JsonProperty("nonScalarModel")]
        public NonScalarModel NonScalarModel { get; set; } = default!;

        /// <summary>
        /// This class contains scalar types in oneOf/anyOf cases.
        /// </summary>
        [JsonProperty("scalarModel")]
        public ScalarModel? ScalarModel { get; set; }
    }
}