
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OAFComplex.Models.Shared
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class ServerResponse
    {

        [JsonProperty("Message")]
        public string? Message { get; set; }

        [JsonProperty("input")]
        public Dictionary<string, Input>? Input { get; set; }

        [JsonProperty("passed")]
        public bool Passed { get; set; } = default!;
    }
}