
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OAFComplex.Models.Operations
{
    using OAFComplex.Models.Shared;
    using OAFComplex.Utils;
    
    public class MixedModelRequest
    {

        /// <summary>
        /// An enum representing what case to receive in receiver endpoints
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=case")]
        public CaseEnum Case { get; set; } = default!;
    }
}