
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OAFComplex.Models.Operations
{
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using OAFComplex.Models.Shared;
    using OAFComplex.Utils;
    using System.Collections.Generic;
    using System.Numerics;
    using System;
    

    public class ResponseBodyType
    {
        private ResponseBodyType(string value) { Value = value; }

        public string Value { get; private set; }
        public static ResponseBodyType ArrayOfAtom { get { return new ResponseBodyType("arrayOfAtom"); } }
        
        public static ResponseBodyType Atom { get { return new ResponseBodyType("Atom"); } }
        
        public static ResponseBodyType Null { get { return new ResponseBodyType("null"); } } 

        public override string ToString() { return Value; }
        public static implicit operator String(ResponseBodyType v) { return v.Value; }
        public static ResponseBodyType FromString(string v) {
            switch(v) {
                case "arrayOfAtom": return ArrayOfAtom;
                case "Atom": return Atom;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for ResponseBodyType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ResponseBodyType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }
    

    [JsonConverter(typeof(ResponseBody.ResponseBodyConverter))]
    public class ResponseBody {
        public ResponseBody(ResponseBodyType type) {
            Type = type;
        }
        public List<Atom>? ArrayOfAtom { get; set; } 
        public Atom? Atom { get; set; } 

        public ResponseBodyType Type {get; set; }


        public static ResponseBody CreateArrayOfAtom(List<Atom> arrayOfAtom) {
            ResponseBodyType typ = ResponseBodyType.ArrayOfAtom;

            ResponseBody res = new ResponseBody(typ);
            res.ArrayOfAtom = arrayOfAtom;
            return res;
        }

        public static ResponseBody CreateAtom(Atom atom) {
            ResponseBodyType typ = ResponseBodyType.Atom;

            ResponseBody res = new ResponseBody(typ);
            res.Atom = atom;
            return res;
        }

        public static ResponseBody CreateNull() {
            ResponseBodyType typ = ResponseBodyType.Null;
            return new ResponseBody(typ);
        }

        public class ResponseBodyConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(ResponseBody);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            { 
                var json = JRaw.Create(reader).ToString();

                if (json == "null") {
                    return null;
                }
                try
                {
                    Atom? atom = JsonConvert.DeserializeObject<Atom>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(Atom), "string")});
                    return new ResponseBody(ResponseBodyType.Atom) {
                        Atom = atom
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    List<Atom>? arrayOfAtom = JsonConvert.DeserializeObject<List<Atom>>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(List<Atom>), "string")});
                    return new ResponseBody(ResponseBodyType.ArrayOfAtom) {
                        ArrayOfAtom = arrayOfAtom
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                ResponseBody res = (ResponseBody)value;
                if (ResponseBodyType.FromString(res.Type).Equals(ResponseBodyType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.ArrayOfAtom != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfAtom));
                    return;
                }
                if (res.Atom != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Atom));
                    return;
                }

            }
        }

    }


}