
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OAFComplex.Models.Operations
{
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using OAFComplex.Utils;
    using System.Numerics;
    using System;
    

    public class ScalarParamResponseBodyType
    {
        private ScalarParamResponseBodyType(string value) { Value = value; }

        public string Value { get; private set; }
        public static ScalarParamResponseBodyType Int32 { get { return new ScalarParamResponseBodyType("int32"); } }
        
        public static ScalarParamResponseBodyType Boolean { get { return new ScalarParamResponseBodyType("boolean"); } }
        
        public static ScalarParamResponseBodyType Str { get { return new ScalarParamResponseBodyType("str"); } }
        
        public static ScalarParamResponseBodyType Any { get { return new ScalarParamResponseBodyType("any"); } }
        
        public static ScalarParamResponseBodyType Null { get { return new ScalarParamResponseBodyType("null"); } } 

        public override string ToString() { return Value; }
        public static implicit operator String(ScalarParamResponseBodyType v) { return v.Value; }
        public static ScalarParamResponseBodyType FromString(string v) {
            switch(v) {
                case "int32": return Int32;
                case "boolean": return Boolean;
                case "str": return Str;
                case "any": return Any;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for ScalarParamResponseBodyType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ScalarParamResponseBodyType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }
    

    [JsonConverter(typeof(ScalarParamResponseBody.ScalarParamResponseBodyConverter))]
    public class ScalarParamResponseBody {
        public ScalarParamResponseBody(ScalarParamResponseBodyType type) {
            Type = type;
        }
        public int? Int32 { get; set; } 
        public bool? Boolean { get; set; } 
        public string? Str { get; set; } 
        public object? Any { get; set; } 

        public ScalarParamResponseBodyType Type {get; set; }


        public static ScalarParamResponseBody CreateInt32(int int32) {
            ScalarParamResponseBodyType typ = ScalarParamResponseBodyType.Int32;

            ScalarParamResponseBody res = new ScalarParamResponseBody(typ);
            res.Int32 = int32;
            return res;
        }

        public static ScalarParamResponseBody CreateBoolean(bool boolean) {
            ScalarParamResponseBodyType typ = ScalarParamResponseBodyType.Boolean;

            ScalarParamResponseBody res = new ScalarParamResponseBody(typ);
            res.Boolean = boolean;
            return res;
        }

        public static ScalarParamResponseBody CreateStr(string str) {
            ScalarParamResponseBodyType typ = ScalarParamResponseBodyType.Str;

            ScalarParamResponseBody res = new ScalarParamResponseBody(typ);
            res.Str = str;
            return res;
        }

        public static ScalarParamResponseBody CreateAny(object any) {
            ScalarParamResponseBodyType typ = ScalarParamResponseBodyType.Any;

            ScalarParamResponseBody res = new ScalarParamResponseBody(typ);
            res.Any = any;
            return res;
        }

        public static ScalarParamResponseBody CreateNull() {
            ScalarParamResponseBodyType typ = ScalarParamResponseBodyType.Null;
            return new ScalarParamResponseBody(typ);
        }

        public class ScalarParamResponseBodyConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(ScalarParamResponseBody);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            { 
                var json = JRaw.Create(reader).ToString();

                if (json == "null") {
                    return null;
                } 
                try {
                    var converted = Convert.ToInt32(json);
                    return new ScalarParamResponseBody(ScalarParamResponseBodyType.Int32) {
                        Int32 = converted
                    };
                } catch (System.FormatException) {
                    // try next option
                } 
                try {
                    var converted = Convert.ToBoolean(json);
                    return new ScalarParamResponseBody(ScalarParamResponseBodyType.Boolean) {
                        Boolean = converted
                    };
                } catch (System.FormatException) {
                    // try next option
                }
                if (json[0] == '"' && json[^1] == '"'){
                    return new ScalarParamResponseBody(ScalarParamResponseBodyType.Str) {
                        Str = json[1..^1]
                    };
                }
                try
                {
                    object? any = JsonConvert.DeserializeObject<object>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(object), "string")});
                    return new ScalarParamResponseBody(ScalarParamResponseBodyType.Any) {
                        Any = any
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                ScalarParamResponseBody res = (ScalarParamResponseBody)value;
                if (ScalarParamResponseBodyType.FromString(res.Type).Equals(ScalarParamResponseBodyType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Int32 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Int32));
                    return;
                }
                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
                if (res.Any != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Any));
                    return;
                }

            }
        }

    }


}