
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace OAFComplex.Models.Operations
{
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using OAFComplex.Utils;
    using System.Numerics;
    using System;
    

    public class SendScalarParamRequestBodyType
    {
        private SendScalarParamRequestBodyType(string value) { Value = value; }

        public string Value { get; private set; }
        public static SendScalarParamRequestBodyType Int32 { get { return new SendScalarParamRequestBodyType("int32"); } }
        
        public static SendScalarParamRequestBodyType Boolean { get { return new SendScalarParamRequestBodyType("boolean"); } }
        
        public static SendScalarParamRequestBodyType Str { get { return new SendScalarParamRequestBodyType("str"); } }
        
        public static SendScalarParamRequestBodyType Any { get { return new SendScalarParamRequestBodyType("any"); } }
        
        public static SendScalarParamRequestBodyType Null { get { return new SendScalarParamRequestBodyType("null"); } } 

        public override string ToString() { return Value; }
        public static implicit operator String(SendScalarParamRequestBodyType v) { return v.Value; }
        public static SendScalarParamRequestBodyType FromString(string v) {
            switch(v) {
                case "int32": return Int32;
                case "boolean": return Boolean;
                case "str": return Str;
                case "any": return Any;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for SendScalarParamRequestBodyType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((SendScalarParamRequestBodyType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }
    

    [JsonConverter(typeof(SendScalarParamRequestBody.SendScalarParamRequestBodyConverter))]
    public class SendScalarParamRequestBody {
        public SendScalarParamRequestBody(SendScalarParamRequestBodyType type) {
            Type = type;
        }
        public int? Int32 { get; set; } 
        public bool? Boolean { get; set; } 
        public string? Str { get; set; } 
        public object? Any { get; set; } 

        public SendScalarParamRequestBodyType Type {get; set; }


        public static SendScalarParamRequestBody CreateInt32(int int32) {
            SendScalarParamRequestBodyType typ = SendScalarParamRequestBodyType.Int32;

            SendScalarParamRequestBody res = new SendScalarParamRequestBody(typ);
            res.Int32 = int32;
            return res;
        }

        public static SendScalarParamRequestBody CreateBoolean(bool boolean) {
            SendScalarParamRequestBodyType typ = SendScalarParamRequestBodyType.Boolean;

            SendScalarParamRequestBody res = new SendScalarParamRequestBody(typ);
            res.Boolean = boolean;
            return res;
        }

        public static SendScalarParamRequestBody CreateStr(string str) {
            SendScalarParamRequestBodyType typ = SendScalarParamRequestBodyType.Str;

            SendScalarParamRequestBody res = new SendScalarParamRequestBody(typ);
            res.Str = str;
            return res;
        }

        public static SendScalarParamRequestBody CreateAny(object any) {
            SendScalarParamRequestBodyType typ = SendScalarParamRequestBodyType.Any;

            SendScalarParamRequestBody res = new SendScalarParamRequestBody(typ);
            res.Any = any;
            return res;
        }

        public static SendScalarParamRequestBody CreateNull() {
            SendScalarParamRequestBodyType typ = SendScalarParamRequestBodyType.Null;
            return new SendScalarParamRequestBody(typ);
        }

        public class SendScalarParamRequestBodyConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(SendScalarParamRequestBody);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            { 
                var json = JRaw.Create(reader).ToString();

                if (json == "null") {
                    return null;
                } 
                try {
                    var converted = Convert.ToInt32(json);
                    return new SendScalarParamRequestBody(SendScalarParamRequestBodyType.Int32) {
                        Int32 = converted
                    };
                } catch (System.FormatException) {
                    // try next option
                } 
                try {
                    var converted = Convert.ToBoolean(json);
                    return new SendScalarParamRequestBody(SendScalarParamRequestBodyType.Boolean) {
                        Boolean = converted
                    };
                } catch (System.FormatException) {
                    // try next option
                }
                if (json[0] == '"' && json[^1] == '"'){
                    return new SendScalarParamRequestBody(SendScalarParamRequestBodyType.Str) {
                        Str = json[1..^1]
                    };
                }
                try
                {
                    object? any = JsonConvert.DeserializeObject<object>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonConverters(typeof(object), "string")});
                    return new SendScalarParamRequestBody(SendScalarParamRequestBodyType.Any) {
                        Any = any
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                SendScalarParamRequestBody res = (SendScalarParamRequestBody)value;
                if (SendScalarParamRequestBodyType.FromString(res.Type).Equals(SendScalarParamRequestBodyType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Int32 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Int32));
                    return;
                }
                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
                if (res.Any != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Any));
                    return;
                }

            }
        }

    }


}